name: Build and release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  export_release:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Export and create release
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.1
      # Ensure that we get the entire project history
      with:
        fetch-depth: 0

      # Job creates release under the same version as the tag
    - name: Get version from tag
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}

    - name: Write version to version file
      shell: bash
      run: |
        echo "${{ steps.tag_version.outputs.TAG_VERSION }}" > ./version.tres

    - name: Export project
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
        relative_project_path: ./
        cache: true
        archive_output: true
        archive_root_folder: true

    - name: Create release
      uses: ncipollo/release-action@1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
